const stateData = () => {
  const stateOptions = [
    {
      label: "آذربایجان شرقی",
      value: [
        "اسكو",
        "اهر",
        "ایلخچی",
        "باسمنج",
        "بستان آباد",
        "بناب",
        "تبريز",
        "تسوج",
        "جلفا",
        "خسروشهر",
        "سراب",
        "سهند",
        "شبستر",
        "صوفیان",
        "مراغه",
        "مرند",
        "ملكان",
        "ممقان",
        "ميانه",
        "هاديشهر",
        "هريس",
        "هشترود",
        "ورزقان",
      ],
      price: 50_000,
    },
    {
      label: "آذربایجان غربی",
      value: [
        "اروميه",
        "اشنويه",
        "بوكان",
        "تكاب",
        "خوي",
        "سر دشت",
        "سلماس",
        "شاهين دژ",
        "ماكو",
        "مهاباد",
        "مياندوآب",
        "نقده",
        "پلدشت",
        "پيرانشهر",
        "چالدران",
      ],
      price: 70_000,
    },
    {
      label: "اردبیل",
      value: [
        "اردبيل",
        "خلخال",
        "مشگين شهر",
        "نمين",
        "نير",
        "پارس آباد",
        "گرمي",
      ],
      price: 100_000,
    },
    {
      label: "اصفهان",
      value: [
        "آران و بيدگل",
        "اردستان",
        "اصفهان",
        "باغ بهادران",
        "تودشک",
        "تيران",
        "حاجي آباد",
        "خميني شهر",
        "خوانسار",
        "درچه",
        "دهاقان",
        "زرين شهر",
        "سميرم",
        "شهرضا",
        "عسگران",
        "علويجه",
        "فلاورجان",
        "كاشان",
        "مباركه",
        "نجف آباد",
        "نطنز",
        "ورزنه",
        "کوهپایه",
        "گلپايگان",
      ],
      price: 90_000,
    },
    {
      label: "ایلام",
      value: [
        "آبدانان",
        "ايلام",
        "ايوان",
        "دره شهر",
        "دهلران",
        "سرابله",
        "مهران",
      ],
      price: 100_000,
    },
    {
      label: "بوشهر",
      value: [
        "اهرم",
        "برازجان",
        "بوشهر",
        "جم",
        "خورموج",
        "دير",
        "عسلویه",
        "كنگان",
        "کاکی",
        "گناوه",
      ],
      price: 120_000,
    },
    {
      label: "تهران",
      value: [
        "اسلامشهر",
        "باقرشهر",
        "بومهن",
        "تجريش",
        "تهران",
        "دماوند",
        "رباط كريم",
        "رودهن",
        "ري",
        "شريف آباد",
        "شهريار",
        "فشم",
        "فيروزكوه",
        "قدس",
        "قرچك",
        "كهريزك",
        "لواسان",
        "ملارد",
        "ورامين",
        "پاكدشت",
        "چهاردانگه",
      ],
      price: 20_000,
    },
    {
      label: "چهارمحال و بختیاری",
      value: ["اردل", "بروجن", "شهركرد", "فارسان", "لردگان", "چلگرد"],
      price: 90_000,
    },

    {
      label: "خراسان رضوی",
      value: [
        "تايباد",
        "تربت جام",
        "تربت حيدريه",
        "خواف",
        "درگز",
        "سبزوار",
        "سرخس",
        "طبس",
        "طرقبه",
        "فريمان",
        "قوچان",
        "كاشمر",
        "مشهد",
        "نيشابور",
        "چناران",
        "گناباد",
      ],
      price: 200_000,
    },
    {
      label: "خوزستان",
      value: [
        "آبادان",
        "انديمشك",
        "اهواز",
        "ايذه",
        "ايرانشهر",
        "باغ ملك",
        "بندر امام خميني",
        "بندر ماهشهر",
        "بهبهان",
        "حمیدیه",
        "خرمشهر",
        "دزفول",
        "رامشیر",
        "رامهرمز",
        "سوسنگرد",
        "شادگان",
        "شادگان",
        "شوش",
        "شوشتر",
        "لالي",
        "مسجد سليمان",
        "ملاثانی",
        "هنديجان",
        "هويزه",
      ],
      price: 120_000,
    },
    {
      label: "سیستان و بلوچستان",
      value: [
        "ايرانشهر",
        "خاش",
        "زابل",
        "زاهدان",
        "سراوان",
        "سرباز",
        "ميرجاوه",
        "چابهار",
      ],
      price: 150_000,
    },
    {
      label: "فارس ",
      value: [
        "آباده",
        "اردكان",
        "ارسنجان",
        "استهبان",
        "اقليد",
        "بوانات",
        "جهرم",
        "حاجي آباد",
        "خرامه",
        "خنج",
        "داراب",
        "زرقان",
        "سروستان",
        "سوريان",
        "سپيدان",
        "شيراز",
        "صفاشهر",
        "فراشبند",
        "فسا",
        "فيروز آباد",
        "كازرون",
        "لار",
        "لامرد",
        "مرودشت",
        "مهر",
        "کوار",
      ],
      price: 150_000,
    },
    {
      label: "کرج ",
      value: [
        "اشتهارد",
        "طالقان",
        "كرج",
        "ماهدشت",
        "نظرآباد",
        "هشتگرد",
        "فردیس",
      ],
      price: 10_000,
    },

    {
      label: "کرمان ",
      value: [
        "انار",
        "بافت",
        "بردسير",
        "بم",
        "جيرفت",
        "راور",
        "رفسنجان",
        "زرند",
        "سيرجان",
        "كرمان",
        "كهنوج",
        "کوهبنان",
      ],
      price: 80_000,
    },
    {
      label: "کرمانشاه ",
      value: [
        "اسلام آباد غرب",
        "جوانرود",
        "سنقر",
        "صحنه",
        "قصر شيرين",
        "كرمانشاه",
        "كنگاور",
        "هرسين",
        "پاوه",
      ],
      price: 150_000,
    },
    {
      label: "گلستان ",
      value: [
        "آزاد شهر",
        "آق قلا",
        "راميان",
        "علي آباد كتول",
        "كردكوی",
        "كلاله",
        "گرگان",
        "گنبد كاووس",
      ],
      price: 150_000,
    },
    {
      label: "گیلان ",
      value: [
        "آستارا",
        "املش",
        "تالش",
        "رشت",
        "رودبار",
        "شفت",
        "صومعه سرا",
        "فومن",
        "لاهیجان",
        "لنگرود",
        "ماسال",
        "ماسوله",
        "منجيل",
        "هشتپر",
      ],
      price: 115_000,
    },
    {
      label: "لرستان ",
      value: [
        "ازنا",
        "الشتر",
        "اليگودرز",
        "بروجرد",
        "خرم آباد",
        "دزفول",
        "دورود",
        "كوهدشت",
        "ماهشهر",
        "نور آباد",
      ],
      price: 90_000,
    },
    {
      label: "مازندران ",
      value: [
        "آمل",
        "بابل",
        "بابلسر",
        "بلده",
        "بهشهر",
        "تنكابن",
        "جويبار",
        "رامسر",
        "ساري",
        "قائم شهر",
        "محمود آباد",
        "نكا",
        "نور",
        "نوشهر",
        "چالوس",
      ],
      price: 150_000,
    },
    {
      label: "هرمزگان ",
      value: [
        "بستك",
        "بندر جاسك",
        "بندر خمیر",
        "بندر لنگه",
        "بندرعباس",
        "حاجي آباد",
        "دهبارز",
        "قشم",
        "قشم",
        "كيش",
        "ميناب",
      ],
      price: 100_000,
    },
    {
      label: "همدان ",
      value: ["اسدآباد", "بهار", "رزن", "ملاير", "نهاوند", "همدان"],
      price: 60_000,
    },
    {
      label: "یزد ",
      value: [
        "ابركوه",
        "اردكان",
        "اشكذر",
        "بافق",
        "تفت",
        "خضرآباد",
        "زارچ",
        "طبس",
        "مهريز",
        "ميبد",
        "هرات",
        "يزد",
      ],
      price: 170_000,
    },
  ];

  return stateOptions;
};

export const productsData = [
  {
    id: 1,
    name: "قهوه اسپرسو ساندرز کلاسیک",
    brand: "Sanders",
    category: "اسپرسو",
    price: 450000,
    discount: 10,
    sales: 230,
    images: ["/images/sanders-espresso.jpg"],
    description: "قهوه اسپرسو با طعم غنی و عطر بینظیر، مناسب برای دستگاه‌های اسپرسوساز",
    createdAt: "2024-12-01",
    rating: 4.8,
    colors: ["کلاسیک", "طلایی"],
    inStock: true,
  },
  {
    id: 2,
    name: "دانه قهوه کلمبیا سوپریمو",
    brand: "Colombian Coffee",
    category: "دانه قهوه",
    price: 680000,
    discount: 0,
    sales: 89,
    images: ["/images/colombia-supremo.jpg"],
    description: "دانه‌های درجه یک قهوه کلمبیا با عطر میوه‌ای و اسیدیته متعادل",
    createdAt: "2024-11-20",
    rating: 4.9,
    colors: ["قهوه‌ای تیره", "کهربایی"],
    inStock: true,
  },
  {
    id: 3,
    name: "قهوه ترک استانبولی",
    brand: "Turkish Coffee",
    category: "قهوه ترک",
    price: 320000,
    discount: 15,
    sales: 156,
    images: ["/images/turkish-coffee.jpg"],
    description: "قهوه ترک اصیل با آسیاب بسیار ریز و طعم سنتی",
    createdAt: "2024-11-15",
    rating: 4.7,
    colors: ["کهربایی", "طلایی"],
    inStock: true,
  },
  {
    id: 4,
    name: "دانه قهوه اتیوپی یرگاچف",
    brand: "Ethiopian Coffee",
    category: "دانه قهوه",
    price: 520000,
    discount: 0,
    sales: 112,
    images: ["/images/ethiopia-yirgacheffe.jpg"],
    description: "دانه قهوه اتیوپی با طعم گلی و مرکباتی، اسیدیته روشن و دلپذیر",
    createdAt: "2024-11-10",
    rating: 4.6,
    colors: ["قهوه‌ای روشن", "طلایی"],
    inStock: true,
  },
  {
    id: 5,
    name: "قهوه فرانسه صبحانه",
    brand: "French Roast",
    category: "قهوه آسیاب شده",
    price: 280000,
    discount: 5,
    sales: 67,
    images: ["/images/french-breakfast.jpg"],
    description: "قهوه فرانسه با برشته کاری تیره و طعم قوی، مناسب صبحانه",
    createdAt: "2024-11-05",
    rating: 4.5,
    colors: ["قهوه‌ای تیره", "برنزی"],
    inStock: true,
  },
  {
    id: 6,
    name: "قهوه سرد کاپوچینو",
    brand: "Cold Brew",
    category: "قهوه سرد",
    price: 380000,
    discount: 8,
    sales: 45,
    images: ["/images/cold-cappuccino.jpg"],
    description: "کاپوچینو سرد با کف شیر خامه‌ای و طعم بینظیر",
    createdAt: "2024-10-28",
    rating: 4.3,
    colors: ["کرمی", "قهوه‌ای روشن"],
    inStock: true,
  },
  {
    id: 7,
    name: "دانه قهوه برزیل سانتوس",
    brand: "Brazil Coffee",
    category: "دانه قهوه",
    price: 490000,
    discount: 12,
    sales: 89,
    images: ["/images/brazil-santos.jpg"],
    description: "دانه قهوه برزیل با طعم شکلاتی و آجیلی، مناسب اسپرسو",
    createdAt: "2024-10-20",
    rating: 4.4,
    colors: ["قهوه‌ای", "کهربایی"],
    inStock: true,
  },
  {
    id: 8,
    name: "قهوه موکا یمنی",
    brand: "Yemen Mocha",
    category: "دانه قهوه",
    price: 750000,
    discount: 5,
    sales: 34,
    images: ["/images/yemen-mocha.jpg"],
    description: "قهوه موکا یمن با طعم شکلاتی و ادویه‌ای، عطری خاص و بی‌نظیر",
    createdAt: "2024-10-15",
    rating: 4.9,
    colors: ["قهوه‌ای تیره", "طلایی"],
    inStock: true,
  },
  {
    id: 9,
    name: "اسپرسو اینتنسو",
    brand: "Lavazza",
    category: "اسپرسو",
    price: 420000,
    discount: 0,
    sales: 78,
    images: ["/images/lavazza-intenso.jpg"],
    description: "اسپرسو ایتالیایی با طعم قوی و کرم غلیظ، عالی برای صبح",
    createdAt: "2024-10-10",
    rating: 4.6,
    colors: ["کلاسیک", "طلایی"],
    inStock: true,
  },
  {
    id: 10,
    name: "قهوه ویتنامی فیلتر",
    brand: "Vietnamese Coffee",
    category: "دانه قهوه",
    price: 360000,
    discount: 0,
    sales: 56,
    images: ["/images/vietnamese-filter.jpg"],
    description: "دانه قهوه ویتنامی مناسب برای فیلتر، با طعم قوی و شیرین",
    createdAt: "2024-10-05",
    rating: 4.7,
    colors: ["قهوه‌ای تیره", "کهربایی"],
    inStock: true,
  },
  {
    id: 11,
    name: "قهوه لاته وانیلی",
    brand: "Vanilla Latte",
    category: "قهوه شیردار",
    price: 350000,
    discount: 0,
    sales: 92,
    images: ["/images/vanilla-latte.jpg"],
    description: "لاته وانیلی با شیر تازه و شربت وانیل، طعمی دلپذیر و شیرین",
    createdAt: "2024-09-28",
    rating: 4.5,
    colors: ["کرمی", "طلایی"],
    inStock: true,
  },
  {
    id: 12,
    name: "دانه قهوه گواتمالا",
    brand: "Guatemala Coffee",
    category: "دانه قهوه",
    price: 560000,
    discount: 10,
    sales: 67,
    images: ["/images/guatemala-coffee.jpg"],
    description: "دانه قهوه گواتمالا با طعم شکلاتی و میوه‌های خشک",
    createdAt: "2024-09-20",
    rating: 4.8,
    colors: ["قهوه‌ای", "کهربایی"],
    inStock: true,
  },
  {
    id: 13,
    name: "قهوه سرد نیترو",
    brand: "Nitro Cold Brew",
    category: "قهوه سرد",
    price: 420000,
    discount: 8,
    sales: 45,
    images: ["/images/nitro-cold-brew.jpg"],
    description: "قهوه سرد نیترو با کف نرم و طعم غنی، تجربه‌ای جدید از قهوه",
    createdAt: "2024-09-15",
    rating: 4.7,
    colors: ["قهوه‌ای تیره", "کرمی"],
    inStock: true,
  },
  {
    id: 14,
    name: "کاپوچینو ایتالیایی",
    brand: "Italian Cappuccino",
    category: "قهوه شیردار",
    price: 380000,
    discount: 5,
    sales: 123,
    images: ["/images/italian-cappuccino.jpg"],
    description: "کاپوچینو ایتالیایی با کف غلیظ و طعم بینظیر، صبحانه سنتی",
    createdAt: "2024-09-10",
    rating: 4.9,
    colors: ["کرمی", "قهوه‌ای روشن"],
    inStock: true,
  },
  {
    id: 15,
    name: "دانه قهوه کنیا AA",
    brand: "Kenya Coffee",
    category: "دانه قهوه",
    price: 590000,
    discount: 0,
    sales: 34,
    images: ["/images/kenya-aa.jpg"],
    description: "دانه قهوه کنیا درجه AA با طعم توت‌های قرمز و اسیدیته بالانس",
    createdAt: "2024-09-05",
    rating: 4.8,
    colors: ["قهوه‌ای روشن", "کهربایی"],
    inStock: true,
  },
  {
    id: 16,
    name: "قهوه عربیکا خالص",
    brand: "Pure Arabica",
    category: "دانه قهوه",
    price: 500000,
    discount: 12,
    sales: 89,
    images: ["/images/pure-arabica.jpg"],
    description: "قهوه عربیکا خالص با عطر گل‌های یاس و طعم میوه‌ای",
    createdAt: "2024-08-28",
    rating: 4.6,
    colors: ["قهوه‌ای", "طلایی"],
    inStock: true,
  },
  {
    id: 17,
    name: "اسپرسو روبوستا",
    brand: "Robusta Espresso",
    category: "اسپرسو",
    price: 380000,
    discount: 0,
    sales: 56,
    images: ["/images/robusta-espresso.jpg"],
    description: "اسپرسو با دانه روبوستا، طعم قوی و کرم غلیظ برای کافئین بالا",
    createdAt: "2024-08-20",
    rating: 4.4,
    colors: ["قهوه‌ای تیره", "کلاسیک"],
    inStock: true,
  },
  {
    id: 18,
    name: "قهوه صبحانه مدیترانه",
    brand: "Mediterranean Coffee",
    category: "قهوه آسیاب شده",
    price: 310000,
    discount: 10,
    sales: 78,
    images: ["/images/mediterranean-breakfast.jpg"],
    description: "قهوه مدیترانه با برشته کاری ملایم و طعم متعادل",
    createdAt: "2024-08-15",
    rating: 4.5,
    colors: ["کهربایی", "برنزی"],
    inStock: true,
  },
  {
    id: 19,
    name: "دانه قهوه سوماترا",
    brand: "Sumatra Coffee",
    category: "دانه قهوه",
    price: 540000,
    discount: 8,
    sales: 45,
    images: ["/images/sumatra-coffee.jpg"],
    description: "دانه قهوه سوماترا با طعم خاکی و گیاهی، عطری خاص و ماندگار",
    createdAt: "2024-08-10",
    rating: 4.7,
    colors: ["قهوه‌ای تیره", "کهربایی"],
    inStock: true,
  },
  {
    id: 20,
    name: "موکاچینو شکلاتی",
    brand: "Chocolate Mochaccino",
    category: "قهوه شیردار",
    price: 370000,
    discount: 15,
    sales: 134,
    images: ["/images/mochaccino.jpg"],
    description: "ترکیب قهوه اسپرسو با شیر و شکلات، طعمی دلپذیر و شیرین",
    createdAt: "2024-08-05",
    rating: 4.3,
    colors: ["قهوه‌ای روشن", "کرمی"],
    inStock: true,
  },
];

export default stateData;
